# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# sf-dep template: https://github.com/edzer/sf_dep/blob/master/.travis.yml

language: r
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev


warnings_are_errors: false
