---
title: "VA Open Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{VA Open Data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

To get the most out of _tidyVA_, it is best to also load the _tidyverse_ package.

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(sf)

#devtools::install_github("iecastro/tidyVA")

#data("sector")
#data("VAloc")

```

```{r}
ptsd <- jsonlite::fromJSON("https://www.data.va.gov/sites/default/files/NEPEC_Overview_PTSD_FY15.json",
                           "text", simplifyDataFrame = TRUE) %>% as.tibble()

ptsd$Value <- as.numeric(ptsd$Value)
```

## Number of Veterans with PTSD by VISN

Lets highlight the Northeastern and Mid-Atlantic regions

```{r}

visn_data <- ptsd %>% filter(Category == "VISN-level Stats" & Item == "N with PTSD")

visn_data %>% mutate(NEMA = case_when(Location %in% c("VISN1","VISN2","VISN4","VISN5","VISN6") ~ "yes",
                                   !Location %in% c("VISN1","VISN2","VISN4","VISN5","VISN6") ~ "no")) %>%
  ggplot(aes(reorder(Location, Value), Value, fill=NEMA)) + 
  geom_col() + coord_flip() + scale_fill_manual(values = c("yes" = "darkred", "no" = "gray50"), guide = FALSE) +
  theme_minimal() + theme(axis.text = element_text(color = "black")) +
  labs(y = "", x = " ") + scale_y_continuous(labels = scales::comma)
  

```


Aggregate simple features to VISN level and merge to data frame

```{r}
visn_geo <- sector %>% filter(VISN %in% c("01","02","04","05","06")) %>% 
  group_by(VISN) %>% summarise()

NEMA <- visn_data %>% filter(Location %in% c("VISN1","VISN2","VISN4","VISN5","VISN6")) %>%
  mutate(VISN = case_when(Location == "VISN1" ~ "01", Location == "VISN2" ~ "02", Location == "VISN4" ~ "04",
                          Location == "VISN5" ~ "05", Location == "VISN" ~ "06"))

visn <- left_join(visn_geo,NEMA, by = "VISN") 

```


```{r}

vha <- VAloc %>% filter(VAAdministration == "VHA") %>% 
  rename(Location = StationNumber) %>% select(Location, Shape)

sites <- ptsd %>% filter(Category == "Station-Level Stats" & Item == "% of Veterans with PTSD that received any MH care") %>% mutate(pct = Value /100)

sites <- left_join(sites,vha, by = "Location") %>% st_as_sf() %>%
  st_intersection(visn)

```



```{r}

ggplot() + geom_sf(data = visn, aes(fill = Value), color = NA) +
    geom_sf(data = visn, fill = NA, color = "#ffffff") +
    geom_sf(data = sites, fill = NA, color = "darkred", aes(size = pct), show.legend = "point") +
    scale_fill_viridis_c(labels = scales::comma) +
    scale_size_continuous(labels = scales::percent)

```

